runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: ssl
  version: latest

handlers:
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/.*

- url: /.*
  script: main.app
