# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: digests.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='digests.proto',
  package='',
  serialized_pb=_b('\n\rdigests.proto\"T\n\x07\x44igests\x12 \n\x07\x64igests\x18\x01 \x03(\x0b\x32\x0f.Digests.Digest\x1a\'\n\x06\x44igest\x12\x0e\n\x06\x64igest\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DIGESTS_DIGEST = _descriptor.Descriptor(
  name='Digest',
  full_name='Digests.Digest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='digest', full_name='Digests.Digest.digest', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Digests.Digest.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=101,
)

_DIGESTS = _descriptor.Descriptor(
  name='Digests',
  full_name='Digests',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='digests', full_name='Digests.digests', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DIGESTS_DIGEST, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=101,
)

_DIGESTS_DIGEST.containing_type = _DIGESTS
_DIGESTS.fields_by_name['digests'].message_type = _DIGESTS_DIGEST
DESCRIPTOR.message_types_by_name['Digests'] = _DIGESTS

Digests = _reflection.GeneratedProtocolMessageType('Digests', (_message.Message,), dict(

  Digest = _reflection.GeneratedProtocolMessageType('Digest', (_message.Message,), dict(
    DESCRIPTOR = _DIGESTS_DIGEST,
    __module__ = 'digests_pb2'
    # @@protoc_insertion_point(class_scope:Digests.Digest)
    ))
  ,
  DESCRIPTOR = _DIGESTS,
  __module__ = 'digests_pb2'
  # @@protoc_insertion_point(class_scope:Digests)
  ))
_sym_db.RegisterMessage(Digests)
_sym_db.RegisterMessage(Digests.Digest)


# @@protoc_insertion_point(module_scope)
